set $mod Mod4
set $menu wmenu-run
bindsym $mod+Space exec $menu

bindgesture swipe:right workspace prev
bindgesture swipe:left workspace next

# Catppuccin Mocha (palette in definitions.d/theme.conf)
# class                 border    background indicator text      child_border
client.focused          $lavender $base      $rosewater $text    $lavender
client.focused_inactive $overlay0 $base      $rosewater $text    $overlay0
client.unfocused        $overlay0 $base      $rosewater $text    $overlay0
client.urgent           $peach    $base      $overlay0  $peach   $peach
client.placeholder      $overlay0 $base      $overlay0  $text    $overlay0
client.background       $base

